name: Apply Sandbox Environment
on:
  push:
    branches:
      - main
jobs:
  include:
    uses: ./.github/workflows/apply-workflow.yaml
    with:
      aws_region: eu-west-1
      environment: sandbox
      iam_role: arn:aws:iam::339713154821:role/aws-resources-apply
